#!/bin/bash

set -eux

cd out

git init .
git config --local user.name nownabe
git config --local user.email nownabe@gmail.com
git checkout -b gh-pages
git add --all
git commit -m ":rocket: Update nownabe.github.io :rocket:"

git remote add origin https://nownabe:${GITHUB_TOKEN}@github.com/nownabe/nownabe.github.io.git
git push -f -u origin gh-pages
