import React from 'react';

import Section from 'common/partials/Section';
import Items from 'common/partials/Items';

const contents = [
  {
    url: 'https://x86-emulator.nownabe.com/',
    title: 'x86 Board',
    description:
      `An emulator of x86 CPU to learn about x86 assembly, created with React/Redux.
      This emulator can execute i386 assembly programs and show data in registers and memory step by step.
      It allows you to learn x86 assembly.`,
  },
  {
    link: '/rubygems',
    title: 'RubyGems',
    description: 'RubyGems I released.',
  },
  {
    url: 'https://github.com/nownabe/cryptography',
    title: 'cryptography',
    description:
      `A simple CLI tool to encrypt/decrypt files with secret password.
      It is written by Golang.`,
  },
  {
    url: 'http://unionfes.tojok-on.com/2015/',
    title: "TOJO K-ON Union Fes '15 Website",
    description:
      `Designed and built a website for a live concert.
      It's responsive and parallax.
      Deployed by Wercker, generated by Middleman.`,
  },
];

export default () => (
  <Section title="Works">
    <Items contents={contents} />
  </Section>
);
