name: Build and Deploy

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: nownabe/nownabe
          path: src
          fetch-depth: 0
      - name: Build HTML
        run: ruby generate.rb
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3


